apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ./../compose.yaml convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ./../compose.yaml convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - image: aadhithya123/backend:c0319586c89d99f8a375b6bba897a2f1c5d3030a
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
