apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ./../compose.yaml convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ./../compose.yaml convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: aadhithya123/frontend:465144a644d67262d888f5ab41e5fe6f2b737d52
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
